package com.enterpriseintellijence.enterpriseintellijence.dto.enums;

public enum ClothingType {
    CLOTHS_JEANS,CLOTHS_DRESS,CLOTHS_SKIRT,CLOTHS_T_SHIRT,CLOTHS_SWEATERS,CLOTHS_TROUSERS,
    SHOES_BOOTS,SHOES_HEELS,SHOES_SPORT,SHOES_TRAINERS,SHOES_SANDALS,
    BAGS_SHOULDER_BAG,BAGS_HANDBAGS,BAGS_LUGGAGE,BAGS_BACKPACKS,
    ACCESSORIES_WATCHES,ACCESSORIES_SUNGLASSES,ACCESSORIES_BELTS,ACCESSORIES_HATS_CAPS
}
