package com.enterpriseintellijence.enterpriseintellijence.dto.enums;

public enum EntertainmentType {
    VIDEOGAMES_CONSOLES_XBOXONE,VIDEOGAMES_CONSOLES_PLAYSTATION_FIVE,VIDEOGAMES_CONSOLES_PLAYSTATION_OLDER,VIDEOGAMES_CONSOLES_PCGAMES,
    MEDIA_MUSIC,MEDIA_VIDEO,
    BOOKS_NON_FICTION,BOOKS_KIDS,BOOKS_LITERATURE,BOOKS_FICTION
}
