package com.enterpriseintellijence.enterpriseintellijence.dto.enums;

public enum HomeType {
    TEXTILES_BLANKETS,TEXTILES_CUSHIONS,TEXTILES_TABLE_LINEN,TEXTILES_TOWEL,TEXTILES_BEDDING,
    HOME_ACCESSORIES_COOKS,HOME_ACCESSORIES_PICTURE,HOME_ACCESSORIES_PHOTO_FRAMES,HOME_ACCESSORIES_STORAGE,HOME_ACCESSORIES_MIRRORS,HOME_ACCESSORIES_VASES,
    TABLEWARE_DINNERWARE,TABLEWARE_CUTLERY,TABLEWARE_DRINKWARE
}
